# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0003_auto_20180622_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
