# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-23 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0005_remove_card_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
