# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-23 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0008_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
